INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023001","Affi","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023002","Albaredo d'Adige","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023003","Angiari","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023004","Arcole","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023005","Badia Calavena","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023006","Bardolino","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023007","Belfiore","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023008","Bevilacqua","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023009","Bonavigo","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023010","Boschi Sant'Anna","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023011","Bosco Chiesanuova","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023012","Bovolone","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023013","Brentino Belluno","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023014","Brenzone sul Garda","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023015","Bussolengo","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023016","Buttapietra","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023017","Caldiero","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023018","Caprino Veronese","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023019","Casaleone","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023020","Castagnaro","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023021","Castel d'Azzano","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023022","Castelnuovo del Garda","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023023","Cavaion Veronese","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023024","Cazzano di Tramigna","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023025","Cerea","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023026","Cerro Veronese","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023027","Cologna Veneta","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023028","Colognola ai Colli","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023029","Concamarise","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023030","Costermano sul Garda","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023031","Dolcè","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023032","Erbè","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023033","Erbezzo","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023034","Ferrara di Monte Baldo","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023035","Fumane","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023036","Garda","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023037","Gazzo Veronese","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023038","Grezzana","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023039","Illasi","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023040","Isola della Scala","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023041","Isola Rizza","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023042","Lavagno","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023043","Lazise","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023044","Legnago","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023045","Malcesine","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023046","Marano di Valpolicella","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023047","Mezzane di Sotto","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023048","Minerbe","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023049","Montecchia di Crosara","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023050","Monteforte d'Alpone","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023051","Mozzecane","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023052","Negrar di Valpolicella ","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023053","Nogara","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023054","Nogarole Rocca","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023055","Oppeano","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023056","Palù","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023057","Pastrengo","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023058","Pescantina","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023059","Peschiera del Garda","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023060","Povegliano Veronese","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023061","Pressana","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023062","Rivoli Veronese","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023063","Roncà","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023064","Ronco all'Adige","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023065","Roverchiara","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023066","Roveredo di Guà","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023067","Roverè Veronese","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023068","Salizzole","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023069","San Bonifacio","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023070","San Giovanni Ilarione","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023071","San Giovanni Lupatoto","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023072","Sanguinetto","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023073","San Martino Buon Albergo","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023074","San Mauro di Saline","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023075","San Pietro di Morubio","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023076","San Pietro in Cariano","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023077","Sant'Ambrogio di Valpolicella","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023078","Sant'Anna d'Alfaedo","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023079","San Zeno di Montagna","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023080","Selva di Progno","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023081","Soave","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023082","Sommacampagna","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023083","Sona","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023084","Sorgà","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023085","Terrazzo","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023086","Torri del Benaco","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023087","Tregnago","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023088","Trevenzuolo","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023089","Valeggio sul Mincio","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023090","Velo Veronese","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023091","Verona","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023092","Veronella","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023093","Vestenanova","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023094","Vigasio","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023095","Villa Bartolomea","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023096","Villafranca di Verona","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023097","Zevio","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("023098","Zimella","Verona");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024001","Agugliaro","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024002","Albettone","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024003","Alonte","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024004","Altavilla Vicentina","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024005","Altissimo","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024006","Arcugnano","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024007","Arsiero","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024008","Arzignano","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024009","Asiago","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024010","Asigliano Veneto","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024012","Bassano del Grappa","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024013","Bolzano Vicentino","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024014","Breganze","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024015","Brendola","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024016","Bressanvido","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024017","Brogliano","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024018","Caldogno","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024019","Caltrano","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024020","Calvene","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024021","Camisano Vicentino","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024022","Campiglia dei Berici","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024024","Carrè","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024025","Cartigliano","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024026","Cassola","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024027","Castegnero","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024028","Castelgomberto","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024029","Chiampo","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024030","Chiuppano","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024032","Cogollo del Cengio","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024034","Cornedo Vicentino","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024035","Costabissara","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024036","Creazzo","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024037","Crespadoro","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024038","Dueville","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024039","Enego","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024040","Fara Vicentino","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024041","Foza","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024042","Gallio","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024043","Gambellara","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024044","Gambugliano","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024046","Grisignano di Zocco","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024047","Grumolo delle Abbadesse","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024048","Isola Vicentina","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024049","Laghi","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024050","Lastebasse","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024051","Longare","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024052","Lonigo","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024053","Lugo di Vicenza","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024055","Malo","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024056","Marano Vicentino","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024057","Marostica","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024060","Montebello Vicentino","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024061","Montecchio Maggiore","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024062","Montecchio Precalcino","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024063","Monte di Malo","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024064","Montegalda","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024065","Montegaldella","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024066","Monteviale","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024067","Monticello Conte Otto","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024068","Montorso Vicentino","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024070","Mussolente","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024071","Nanto","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024072","Nogarole Vicentino","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024073","Nove","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024074","Noventa Vicentina","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024075","Orgiano","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024076","Pedemonte","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024077","Pianezze","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024078","Piovene Rocchette","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024079","Pojana Maggiore","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024080","Posina","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024081","Pove del Grappa","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024082","Pozzoleone","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024083","Quinto Vicentino","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024084","Recoaro Terme","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024085","Roana","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024086","Romano d'Ezzelino","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024087","Rosà","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024088","Rossano Veneto","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024089","Rotzo","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024090","Salcedo","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024091","Sandrigo","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024094","San Pietro Mussolino","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024095","Santorso","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024096","San Vito di Leguzzano","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024097","Sarcedo","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024098","Sarego","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024099","Schiavon","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024100","Schio","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024101","Solagna","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024102","Sossano","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024103","Sovizzo","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024104","Tezze sul Brenta","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024105","Thiene","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024106","Tonezza del Cimone","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024107","Torrebelvicino","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024108","Torri di Quartesolo","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024110","Trissino","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024111","Valdagno","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024112","Valdastico","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024113","Valli del Pasubio","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024115","Velo d'Astico","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024116","Vicenza","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024117","Villaga","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024118","Villaverla","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024119","Zanè","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024120","Zermeghedo","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024121","Zovencedo","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024122","Zugliano","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024123","Val Liona","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024124","Barbarano Mossano","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024125","Valbrenta","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024126","Colceresa","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("024127","Lusiana Conco","Vicenza");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025001","Agordo","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025002","Alano di Piave","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025003","Alleghe","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025004","Arsiè","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025005","Auronzo di Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025006","Belluno","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025007","Borca di Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025008","Calalzo di Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025010","Cencenighe Agordino","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025011","Cesiomaggiore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025012","Chies d'Alpago","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025013","Cibiana di Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025014","Colle Santa Lucia","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025015","Comelico Superiore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025016","Cortina d'Ampezzo","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025017","Danta di Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025018","Domegge di Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025019","Falcade","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025021","Feltre","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025022","Fonzaso","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025023","Canale d'Agordo","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025025","Gosaldo","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025026","Lamon","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025027","La Valle Agordina","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025029","Limana","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025030","Livinallongo del Col di Lana","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025032","Lorenzago di Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025033","Lozzo di Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025035","Ospitale di Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025036","Pedavena","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025037","Perarolo di Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025039","Pieve di Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025040","Ponte nelle Alpi","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025043","Rivamonte Agordino","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025044","Rocca Pietore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025045","San Gregorio nelle Alpi","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025046","San Nicolò di Comelico","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025047","San Pietro di Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025048","Santa Giustina","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025049","San Tomaso Agordino","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025050","Santo Stefano di Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025051","San Vito di Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025053","Sedico","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025054","Selva di Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025055","Seren del Grappa","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025056","Sospirolo","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025057","Soverzene","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025058","Sovramonte","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025059","Taibon Agordino","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025060","Tambre","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025062","Vallada Agordina","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025063","Valle di Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025065","Vigo di Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025066","Vodo Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025067","Voltago Agordino","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025069","Zoppè di Cadore","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025070","Quero Vas","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025071","Longarone","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025072","Alpago","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025073","Val di Zoldo","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("025074","Borgo Valbelluna","Belluno");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026001","Altivole","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026002","Arcade","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026003","Asolo","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026004","Borso del Grappa","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026005","Breda di Piave","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026006","Caerano di San Marco","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026007","Cappella Maggiore","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026008","Carbonera","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026009","Casale sul Sile","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026010","Casier","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026011","Castelcucco","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026012","Castelfranco Veneto","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026013","Castello di Godego","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026014","Cavaso del Tomba","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026015","Cessalto","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026016","Chiarano","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026017","Cimadolmo","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026018","Cison di Valmarino","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026019","Codognè","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026020","Colle Umberto","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026021","Conegliano","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026022","Cordignano","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026023","Cornuda","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026025","Crocetta del Montello","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026026","Farra di Soligo","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026027","Follina","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026028","Fontanelle","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026029","Fonte","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026030","Fregona","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026031","Gaiarine","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026032","Giavera del Montello","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026033","Godega di Sant'Urbano","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026034","Gorgo al Monticano","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026035","Istrana","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026036","Loria","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026037","Mansuè","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026038","Mareno di Piave","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026039","Maser","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026040","Maserada sul Piave","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026041","Meduna di Livenza","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026042","Miane","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026043","Mogliano Veneto","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026044","Monastier di Treviso","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026045","Monfumo","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026046","Montebelluna","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026047","Morgano","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026048","Moriago della Battaglia","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026049","Motta di Livenza","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026050","Nervesa della Battaglia","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026051","Oderzo","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026052","Ormelle","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026053","Orsago","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026055","Paese","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026056","Pederobba","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026057","Pieve di Soligo","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026058","Ponte di Piave","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026059","Ponzano Veneto","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026060","Portobuffolè","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026061","Possagno","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026062","Povegliano","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026063","Preganziol","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026064","Quinto di Treviso","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026065","Refrontolo","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026066","Resana","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026067","Revine Lago","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026068","Riese Pio X","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026069","Roncade","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026070","Salgareda","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026071","San Biagio di Callalta","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026072","San Fior","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026073","San Pietro di Feletto","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026074","San Polo di Piave","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026075","Santa Lucia di Piave","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026076","San Vendemiano","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026077","San Zenone degli Ezzelini","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026078","Sarmede","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026079","Segusino","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026080","Sernaglia della Battaglia","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026081","Silea","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026082","Spresiano","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026083","Susegana","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026084","Tarzo","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026085","Trevignano","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026086","Treviso","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026087","Valdobbiadene","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026088","Vazzola","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026089","Vedelago","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026090","Vidor","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026091","Villorba","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026092","Vittorio Veneto","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026093","Volpago del Montello","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026094","Zenson di Piave","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026095","Zero Branco","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("026096","Pieve del Grappa","Treviso");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027001","Annone Veneto","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027002","Campagna Lupia","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027003","Campolongo Maggiore","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027004","Camponogara","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027005","Caorle","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027006","Cavarzere","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027007","Ceggia","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027008","Chioggia","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027009","Cinto Caomaggiore","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027010","Cona","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027011","Concordia Sagittaria","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027012","Dolo","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027013","Eraclea","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027014","Fiesso d'Artico","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027015","Fossalta di Piave","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027016","Fossalta di Portogruaro","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027017","Fossò","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027018","Gruaro","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027019","Jesolo","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027020","Marcon","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027021","Martellago","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027022","Meolo","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027023","Mira","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027024","Mirano","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027025","Musile di Piave","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027026","Noale","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027027","Noventa di Piave","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027028","Pianiga","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027029","Portogruaro","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027030","Pramaggiore","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027031","Quarto d'Altino","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027032","Salzano","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027033","San Donà di Piave","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027034","San Michele al Tagliamento","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027035","Santa Maria di Sala","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027036","San Stino di Livenza","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027037","Scorzè","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027038","Spinea","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027039","Stra","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027040","Teglio Veneto","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027041","Torre di Mosto","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027042","Venezia","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027043","Vigonovo","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("027044","Cavallino-Treporti","Venezia");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028001","Abano Terme","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028002","Agna","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028003","Albignasego","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028004","Anguillara Veneta","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028005","Arquà Petrarca","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028006","Arre","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028007","Arzergrande","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028008","Bagnoli di Sopra","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028009","Baone","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028010","Barbona","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028011","Battaglia Terme","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028012","Boara Pisani","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028013","Borgoricco","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028014","Bovolenta","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028015","Brugine","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028016","Cadoneghe","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028017","Campodarsego","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028018","Campodoro","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028019","Camposampiero","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028020","Campo San Martino","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028021","Candiana","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028022","Carceri","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028023","Carmignano di Brenta","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028026","Cartura","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028027","Casale di Scodosia","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028028","Casalserugo","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028029","Castelbaldo","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028030","Cervarese Santa Croce","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028031","Cinto Euganeo","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028032","Cittadella","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028033","Codevigo","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028034","Conselve","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028035","Correzzola","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028036","Curtarolo","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028037","Este","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028038","Fontaniva","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028039","Galliera Veneta","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028040","Galzignano Terme","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028041","Gazzo","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028042","Grantorto","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028043","Granze","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028044","Legnaro","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028045","Limena","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028046","Loreggia","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028047","Lozzo Atestino","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028048","Maserà di Padova","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028049","Masi","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028050","Massanzago","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028052","Megliadino San Vitale","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028053","Merlara","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028054","Mestrino","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028055","Monselice","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028056","Montagnana","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028057","Montegrotto Terme","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028058","Noventa Padovana","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028059","Ospedaletto Euganeo","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028060","Padova","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028061","Pernumia","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028062","Piacenza d'Adige","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028063","Piazzola sul Brenta","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028064","Piombino Dese","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028065","Piove di Sacco","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028066","Polverara","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028067","Ponso","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028068","Pontelongo","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028069","Ponte San Nicolò","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028070","Pozzonovo","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028071","Rovolon","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028072","Rubano","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028073","Saccolongo","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028075","San Giorgio delle Pertiche","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028076","San Giorgio in Bosco","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028077","San Martino di Lupari","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028078","San Pietro in Gu","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028079","San Pietro Viminario","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028080","Santa Giustina in Colle","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028082","Sant'Angelo di Piove di Sacco","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028083","Sant'Elena","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028084","Sant'Urbano","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028085","Saonara","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028086","Selvazzano Dentro","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028087","Solesino","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028088","Stanghella","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028089","Teolo","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028090","Terrassa Padovana","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028091","Tombolo","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028092","Torreglia","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028093","Trebaseleghe","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028094","Tribano","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028095","Urbana","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028096","Veggiano","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028097","Vescovana","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028098","Vighizzolo d'Este","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028099","Vigodarzere","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028100","Vigonza","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028101","Villa del Conte","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028102","Villa Estense","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028103","Villafranca Padovana","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028104","Villanova di Camposampiero","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028105","Vo'","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028106","Due Carrare","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("028107","Borgo Veneto","Padova");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029001","Adria","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029002","Ariano nel Polesine","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029003","Arquà Polesine","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029004","Badia Polesine","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029005","Bagnolo di Po","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029006","Bergantino","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029007","Bosaro","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029008","Calto","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029009","Canaro","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029010","Canda","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029011","Castelguglielmo","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029012","Castelmassa","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029013","Castelnovo Bariano","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029014","Ceneselli","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029015","Ceregnano","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029017","Corbola","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029018","Costa di Rovigo","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029019","Crespino","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029021","Ficarolo","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029022","Fiesso Umbertiano","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029023","Frassinelle Polesine","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029024","Fratta Polesine","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029025","Gaiba","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029026","Gavello","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029027","Giacciano con Baruchella","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029028","Guarda Veneta","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029029","Lendinara","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029030","Loreo","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029031","Lusia","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029032","Melara","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029033","Occhiobello","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029034","Papozze","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029035","Pettorazza Grimani","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029036","Pincara","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029037","Polesella","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029038","Pontecchio Polesine","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029039","Porto Tolle","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029040","Rosolina","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029041","Rovigo","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029042","Salara","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029043","San Bellino","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029044","San Martino di Venezze","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029045","Stienta","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029046","Taglio di Po","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029047","Trecenta","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029048","Villadose","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029049","Villamarzana","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029050","Villanova del Ghebbo","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029051","Villanova Marchesana","Rovigo");
INSERT INTO comune(istat,nomeComune,provincia) VALUES ("029052","Porto Viro","Rovigo");
